# https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md
debug = true
# [registry."myregistry.com"]
#   ca=["/etc/certs/myregistry.pem"]
#   [[registry."myregistry.com".keypair]]
#     key="/etc/certs/myregistry_key.pem"
#     cert="/etc/certs/myregistry_cert.pem"
[registry."192.168.1.245:32000"]
  http = true
  insecure = true