apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-arch-container-rust
  labels:
    app: multi-arch-container-rust
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: multi-arch-container-rust
  template:
    metadata:
      labels:
        app: multi-arch-container-rust
    spec:
      containers:
      - name: primary
        image: 192.168.1.245:32000/multi-arch-container-rust:registry
        imagePullPolicy: Always
        env:
        - name: "APP_ENVIRONMENT"
          value: "prd"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
