name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "preview/**"
    paths-ignore:
      # - .github
      # - .scripts
      # - .charts
      - kustomize
      - LICENSE
      - README.md
      - build.sh
      - build.ps1
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  IMAGE_NAME: multi-arch-container-rust

jobs:
  versioning:
    uses: ./.github/workflows/versioning.yml

jobs:
  versioning:
    uses: ./.github/workflows/versioning.yml

  app:
    uses: ./.github/workflows/build-app.yml
    needs: versioning
    with:
      fullSemVer: ${{ needs.versioning.outputs.fullSemVer }}

  image:
    uses: ./.github/workflows/build-image.yml
    needs: [versioning, app]
    with:
      semVer: ${{ needs.versioning.outputs.semVer }}




  release:
    needs: [build_app, build_image, push_chart]]
    if: github.ref == 'refs/heads/main'
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    with:
      tag-prefix: ''
      move-major-tag: false